README.md
pubspec.yaml

add badge and bump pubspec

---

example/lib/middleware/creation_middleware.dart
example/lib/react_example/module.dart
example/lib/reducers/app_state.dart
example/lib/reducers/app_state.g.dart
example/lib/reducers/groups.dart
example/lib/reducers/groups.g.dart
example/lib/reducers/todos.dart
lib/generator.dart
lib/src/built_reducer.dart

move currentGroupId and currentGroup to groupsReducer
make appendCode private

move currentGroupId and currentGroup to groupsReducer

---

example/pubspec.lock
example/pubspec.yaml
pubspec.yaml

update example pubspec to pull in react-built-redux from git

update example pubspec to pull in react-built-redux from git

---

README.md
lib/generator.dart
pubspec.yaml

fix case where nested generics in action payload would not gen action name generic correctly

fix_generic_parse

---

lib/src/store.dart
pubspec.yaml

Fix store change generic 
widen analyzer version range

Fix store change generic

---

README.md
lib/built_redux.dart
lib/src/state_transformer.dart
lib/src/store.dart
test/unit/redux_test.dart
test/unit/test_counter.dart
test/unit/test_counter.g.dart

add state transformer

---

lib/generator.dart
pubspec.yaml
test/unit/test_counter.g.dart

type checking improvements for action names

typed_action_name_assignment

---

lib/src/action.dart
pubspec.yaml
test/unit/redux_test.dart

addresses https://github.com/davidmarne/built_redux/issues/31

Optional action payload

---

pubspec.yaml

https://github.com/davidmarne/built_redux/issues/43

allow built_collection 2.0

---

CHANGELOG.md
LICENSE
README.md
pubspec.yaml

* add changelog
* update readme to include link to todoMVC repo

7.3.3 - Add Changelog

---

test/unit/middleware_test.dart
test/unit/store_test.dart
test/unit/test_counter.dart
test/unit/test_counter.g.dart

rename BaseCounter to Counter
fix substate stream tests to actualy fail if other action is called
add await dispose test

test cleanup

---

pubspec.yaml
test/unit/action_generics_models.g.dart
test/unit/collection_models.g.dart
test/unit/inheritance_test_models.g.dart
test/unit/nested_models.g.dart
test/unit/test_counter.g.dart

allow 3.0.0 of built_collection - no breaking changes affect built_redux's usage of built_collection
regen test code

open_built_collection_range_3.0.0

---

lib/src/middleware.dart

I find it useful like the reducer combine method.

* add combine method to middleware

---

CHANGELOG.md
example/example.g.dart
lib/generator.dart
pubspec.yaml
test/unit/action_generics_models.g.dart
test/unit/collection_models.g.dart
test/unit/inheritance_test_models.g.dart
test/unit/nested_models.g.dart
test/unit/test_counter.g.dart

add lint ignores for common lints that cause issues in the generated files

Lint ignores

---

CHANGELOG.md
lib/generator.dart
pubspec.yaml

fix_typedef_generation

---

doc/basics/testing.md
lib/built_redux_test_utils.dart
test/unit/built_redux_test_utils_test.dart

Noticed this typo in a recent PR, figured it's an easy fix :)

Fix verifier typo

---

CHANGELOG.md
pubspec.yaml

forgot to update pubspec version in https://github.com/davidmarne/built_redux/pull/122

7.5.4 update pubspec

---

lib/src/middleware.dart
lib/src/reducer_builder.dart

To resolve some odd dart2js failures, add the workaround given in https://github.com/dart-lang/sdk/issues/38927

Add dart2js workaround for nested builders

---

CHANGELOG.md
pubspec.yaml

allow built value 7
restrict analyzer version

Open built value range

---

pubspec.yaml

Widen analyzer range to include 0.39.x

---

lib/src/action.dart

using like:
```
Observable getConfig(Observable<Action<dynamic>> stream,
MiddlewareApi<AppState, AppStateBuilder, AppActions> api) {
return stream
.where((action)=> action == api.actions.cmsActions.getConfig.name)
```
for find this code when "Find All Reference" of  action "getConfig"

feat: add name to ActionDispatcher for "Find All Reference"

---

.github/workflows/dart_ci.yaml
example/example.g.dart
lib/generator.dart
pubspec.yaml
test/unit/action_generics_models.g.dart
test/unit/collection_models.g.dart
test/unit/inheritance_test_models.g.dart
test/unit/nested_models.g.dart
test/unit/test_counter.g.dart

Analyzer 5

---

.github/workflows/auto_publish.yaml
.github/workflows/dart_ci.yaml

Fix up Github Actions workflows by
- generate an SBOM
- auto publish on releases
- remove dart 2.18 and stable from matrix (will add back Dart 3 later)

Fix up github workflows

---

analysis_options.yaml

This PR bumps/adds workiva_analysis_options to v2. This is being done in an effort to adopt consistency in
`analysis_options.yaml` files across the codebase, and ensure all developers are using the most up to date
functionality that the dart analyzer can provide.
Failing CI will be evaluated by someone from FEDX and resolved. We will reach out when the pr is ready for review.
If you have any questions, concerns, or opinions, please reach out to #support-frontend-dx.
[_Created by Sourcegraph batch change `Workiva/workiva_analysis_options_v2`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/workiva_analysis_options_v2)

Workiva Analysis Options v2
